-- Auto-generated by scripts/import-carta-employees.mjs
-- DO NOT EDIT BY HAND — re-run the script if CSV changes

BEGIN;

-- Resolve Carta tenant id
DO $$
DECLARE v_tenant UUID;
BEGIN
  SELECT id INTO v_tenant FROM tenants WHERE slug = 'carta-d-o-o' LIMIT 1;
  IF v_tenant IS NULL THEN RAISE EXCEPTION 'Carta d.o.o. tenant nije pronađen'; END IF;

  -- ── Seed work_positions iz distinct Carta radnih mjesta ──
  -- ON CONFLICT na (tenant_id, name) bi trebao postojati, ali trenutno nema UNIQUE constraint.
  -- Koristimo defenzivni INSERT ... WHERE NOT EXISTS.
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Asistent', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Asistent');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Asistent prodaje i logistike', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Asistent prodaje i logistike');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Back Office Manager', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Back Office Manager');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Domaćica', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Domaćica');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Koordinator održavanja', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Koordinator održavanja');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Koordinator proizvodnje', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Koordinator proizvodnje');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Radnik na slaganju', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Skladištar', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Skladištar');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Strojar', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Strojar 2. grupe - bottomer', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar 2. grupe - bottomer');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Strojar 3. grupe - bottomer', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar 3. grupe - bottomer');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Voditelj održavanja', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj održavanja');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Voditelj preprinta', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj preprinta');
  INSERT INTO work_positions (tenant_id, name, status)
    SELECT v_tenant, 'Voditelj stroja', 'active'
    WHERE NOT EXISTS (SELECT 1 FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja');

  -- ── Insert workers ──
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Ena', 'Šmaholc', 'ena.smaholc@carta.hr', NULL, 'Postava 5', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Bruno', 'Živković', 'bruno.zivkovic@carta.hr', NULL, 'Postava 1', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Daria', 'Švajhofer', 'daria.svajhofer@carta.hr', NULL, 'Postava 4', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Mirjana', 'Popović', 'mirjana.popovic@carta.hr', NULL, 'Postava 5', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Zoran', 'Kukić', 'kukic.zoran@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Zoran', 'Kovač', 'kovac.zoran@carta.hr', NULL, 'Postava 3', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Franjo', 'Žalac', 'zalac.franjo@carta.hr', NULL, 'Skladište', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Iva', 'Ivković', 'ivkovic.iva@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Asistent'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Valentin', 'Varga', 'valentin.varga@carta.hr', NULL, 'Postava 8', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Anita', 'Cvetković', 'anita.cvetkovic@carta.hr', NULL, 'Postava 3', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Hrvoje', 'Andraković', 'hrvoje.andrakovic@carta.hr', NULL, 'Postava 5', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Milan', 'Josić', 'milan.josic@carta.hr', NULL, 'Voditelj održavanja', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj održavanja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Milan', 'Uglješić', 'milan.ugljesic@carta.hr', NULL, 'Koordinator održavanja', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Koordinator održavanja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Milena', 'Miletić', 'miletic.milena@carta.hr', NULL, 'Postava 1', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Kristina', 'Čubela', 'cubela.kristina@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Back Office Manager'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Dragan', 'Jerković', 'dragan.jerkovic@carta.hr', NULL, 'Postava 2', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Stjepan', 'Grgurić', 'stjepan.grguric@carta.hr', NULL, 'Postava 4', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Matej', 'Galunić', 'matej.galunic@carta.hr', NULL, 'Postava 7', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Ivana', 'Cickai', 'cickai.ivana@carta.hr', NULL, 'Postava 4', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Dragan', 'Đurišić', 'dragan.durisic@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'former');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Biljana', 'Džakula', 'biljana.dzakula@carta.hr', NULL, NULL, NULL, 'former');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Mihael', 'Živković', 'mihael.zivkovic@carta.hr', NULL, 'Postava 2', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Bojan', 'Jager', 'bojan.jager@carta.hr', NULL, 'Postava 4', NULL, 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Sara', 'Ilić', 'sara.ilic@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'former');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Josip', 'Brtan', 'josip.brtan@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'former');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Andrej', 'Merkaš', 'merkas.andrej@carta.hr', NULL, 'Postava 9', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Ida', 'Vidaković', 'ida.vidakovic@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'former');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Vedran', 'Milić', 'vedran.milic@carta.hr', NULL, 'Skladište', NULL, 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Dajana', 'Berković', 'berkovic.dajana@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'former');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Mirta', 'Šipoš', 'mirta.sipos@carta.hr', NULL, 'Postava 1', NULL, 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Katarina', 'Živković', 'katarina.zivkovic@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Asistent prodaje i logistike'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Josip', 'Ervačić', 'josip.ervacic@carta.hr', NULL, 'Postava 5', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Slađana', 'Popović', 'popovic.sladana@carta.hr', NULL, 'Postava 2', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Damir', 'Kapetinić', 'damir.kapetinic@carta.hr', NULL, 'Postava 5', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar 3. grupe - bottomer'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Goran', 'Skender', 'goran.skender@carta.hr', NULL, NULL, NULL, 'former');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Ljubica', 'Musić', 'ljubica.music@carta.hr', NULL, 'Postava 4', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Slavko', 'Vugec', 'slavko.vugec@carta.hr', NULL, 'Postava 1', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Dino', 'Miljatović', 'miljatovic.dino@carta.hr', NULL, 'Postava 2', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Dragana', 'Popović', 'dragana.popovic@carta.hr', NULL, 'Postava 1', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Josip', 'Lončarić', 'josip.loncaric@carta.hr', NULL, 'Postava 1', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Mario', 'Vuksanić', 'mario.vuksanic@carta.hr', NULL, 'Skladište', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Ivica', 'Ečimović', 'ivica.ecimovic@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar 2. grupe - bottomer'), 'former');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Matija', 'Durmić', 'matija.durmic@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Ivan', 'Parlov', 'ivan.parlov@carta.hr', NULL, 'Postava 3', NULL, 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Aleksandra', 'Marić', 'maric.aleksandra@carta.hr', NULL, 'Postava 2', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Emanuela', 'Kujundžić', 'emanuela.kujundzic@carta.hr', NULL, 'Postava 3', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Danijel', 'Mrkšić', 'mrksic.danijel@carta.hr', NULL, 'Postava 1', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Irina', 'Marodt', 'irina.marodt@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Skladištar'), 'former');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Branimir', 'Komić', 'branimir.komic@carta.hr', NULL, 'Postava 4', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Drago', 'Popović', 'drago.popovic@carta.hr', NULL, 'Postava 3', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Mirjana', 'Petrović', 'mirjana.petrovic@carta.hr', NULL, 'Postava 2', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Saša', 'Davidović', 'davidovic.sasa@carta.hr', NULL, 'Administracija', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Koordinator proizvodnje'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Ivan', 'Schrödel', 'ivan.schrodel@carta.hr', NULL, 'Postava 3', NULL, 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Vedran', 'Popić', 'vedran.popic@carta.hr', NULL, 'Postava 5', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Marko', 'Kamenicki', 'marko.kamenicki@carta.hr', NULL, 'Postava 7', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj preprinta'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Marica', 'Kovačić', 'marica.kovacic@carta.hr', NULL, NULL, (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Domaćica'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Matej', 'Budeš', 'matej.budes@carta.hr', NULL, 'Postava 2', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Radoš', 'Rabrenović', 'rabrenovic.rados@carta.hr', NULL, 'Postava 9', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Strojar'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Michelle', 'Ann Zugor', 'zugor.michelleann@carta.hr', NULL, 'Postava 3', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Radnik na slaganju'), 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Kristian', 'Kujundžić', 'kristian.kujundzic@carta.hr', NULL, 'Skladište', NULL, 'active');
  INSERT INTO workers (tenant_id, first_name, last_name, email, phone, department, position_id, status)
    VALUES (v_tenant, 'Josip', 'Marić', 'josip.maric@carta.hr', NULL, 'Postava 8', (SELECT id FROM work_positions WHERE tenant_id = v_tenant AND name = 'Voditelj stroja'), 'active');

  -- ── Update tenant employee_count na stvarni broj active radnika ──
  UPDATE tenants SET employee_count = (SELECT count(*) FROM workers WHERE tenant_id = v_tenant AND status = 'active') WHERE id = v_tenant;
END $$;

COMMIT;
Parsed 61 employees (52 active, 9 former)
Distinct positions: 14
Positions: Asistent, Asistent prodaje i logistike, Back Office Manager, Domaćica, Koordinator održavanja, Koordinator proizvodnje, Radnik na slaganju, Skladištar, Strojar, Strojar 2. grupe - bottomer, Strojar 3. grupe - bottomer, Voditelj održavanja, Voditelj preprinta, Voditelj stroja
